version: "3.8"
services:
  mongo-db:
    image: mongo:latest
    container_name: mongoDB
    ports:
      - 27017:27017
    environment: 
      MONGO_INITDB_ROOT_USERNAME: admin 
      MONGO_INITDB_ROOT_PASSWORD: Welcome1080

